select * from heart;

select decode(sex,0,"FEMALE"),decode(target,0,"NO_DISEASE"),count(1) 
from heart group by sex,target;

#GROUPED BY SEX AND TARGET
select CASE WHEN SEX=0 THEN "FEMALE" ELSE "MALE" END AS SEX,CASE WHEN TARGET=0 THEN "NO_DISEASE"
ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by sex,target;

#GROUPED BY CP AND TARGET
select CASE WHEN cp=0 THEN "VERY LOW"  WHEN cp=1 THEN "LOW" WHEN cp=2 THEN "HIGH" WHEN cp=3 THEN "VERY HIGH" END AS CHEST_PAIN,
CASE WHEN TARGET=0 THEN "NO_DISEASE" ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by cp,target ORDER BY 2;


#GROUPED BY FBS AND TARGET
select CASE WHEN fbs=0 THEN "LESS THAN 120" ELSE "GREATER THAN 120" END AS SUGAR_LEVEL,CASE WHEN TARGET=0 THEN "NO_DISEASE"
ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by fbs,target;


#GROUPED BY restecg AND TARGET
select CASE WHEN restecg=0 THEN "VERY LOW"  WHEN restecg=1 THEN "LOW" WHEN restecg=2 THEN "HIGH" END AS "REST_ECG",
CASE WHEN TARGET=0 THEN "NO_DISEASE" ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by restecg,target ORDER BY 2;


#GROUPED BY exang AND TARGET
select CASE WHEN exang=0 THEN "EXANG_YES" ELSE "EXANG_NO" END AS SUGAR_LEVEL,CASE WHEN TARGET=0 THEN "NO_DISEASE"
ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by exang,target;

#GROUPED BY SLOPE AND TARGET
select CASE WHEN slope=0 THEN "UPSLOPE"  WHEN slope=1 THEN "FLAT" WHEN slope=2 THEN "DOWNSLOPE"  END AS "SLOPE",
CASE WHEN TARGET=0 THEN "NO_DISEASE" ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by slope,target ORDER BY 2,1;


#GROUPED BY CP AND TARGET
select CASE WHEN thal=0 THEN "VERY LOW"  WHEN thal=1 THEN "LOW" WHEN thal=2 THEN "HIGH" WHEN thal=3 THEN "VERY HIGH" END AS thalassemia,
CASE WHEN TARGET=0 THEN "NO_DISEASE" ELSE "YES_DISEASE" END AS DIAGNOSIS,count(1) 
from heart group by thal,target ORDER BY 2;



